# Generated by Django 5.2.4 on 2025-07-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attacks',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('at_type', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField(default=10)),
                ('accuracy', models.IntegerField(default=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('poke_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('poke_type', models.CharField(max_length=50)),
                ('health', models.IntegerField(default=100)),
                ('attack', models.IntegerField(default=10)),
                ('defense', models.IntegerField(default=10)),
                ('speed', models.IntegerField(default=10)),
                ('precision', models.IntegerField(default=100)),
                ('esquive', models.IntegerField(default=5)),
                ('img', models.ImageField(default='pokemon_images/default.png', upload_to='pokemon_images/')),
                ('attack1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack1', to='menu.attacks')),
                ('attack2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack2', to='menu.attacks')),
                ('attack3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack3', to='menu.attacks')),
                ('attack4', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack4', to='menu.attacks')),
            ],
        ),
    ]
