# Generated by Django 5.2.4 on 2025-07-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('at_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('damage', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='esquive',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='precision',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack1', to='menu.attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack2', to='menu.attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack3', to='menu.attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='attack4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack4', to='menu.attack'),
        ),
        migrations.AddField(
            model_name='attack',
            name='at_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.type'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='poke_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.type'),
        ),
        migrations.DeleteModel(
            name='Attacks',
        ),
    ]
